from enum import StrEnum


class ErrorType(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    BAD_TOKEN = "BAD_TOKEN"
    ACCESS_DENIED = "ACCESS_DENIED"
